name: puzztool Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js 24.x
        uses: actions/setup-node@v7
        with:
          node-version: 24.x
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          cname: puzztool.com
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
